<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.7 Estimando contrastes en encuestas de hogares | Análisis de encuestas con R</title>
  <meta name="description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="4.7 Estimando contrastes en encuestas de hogares | Análisis de encuestas con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="github-repo" content="psirusteam/2021ASDA" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.7 Estimando contrastes en encuestas de hogares | Análisis de encuestas con R" />
  
  <meta name="twitter:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  

<meta name="author" content="Andrés Gutiérrez,Stalyn Guerrero, Cristian Téllez, Giovany Babativa" />


<meta name="date" content="2025-11-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estimación-de-razones.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis de encuestas con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="chapter" data-level="1" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="conceptos-básicos-en-encuestas-de-hogares.html"><a href="conceptos-básicos-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>2</b> Conceptos básicos en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="universo-de-estudio-y-población-objetivo.html"><a href="universo-de-estudio-y-población-objetivo.html"><i class="fa fa-check"></i><b>2.1</b> Universo de estudio y población objetivo</a></li>
<li class="chapter" data-level="2.2" data-path="unidades-de-análisis.html"><a href="unidades-de-análisis.html"><i class="fa fa-check"></i><b>2.2</b> Unidades de análisis</a></li>
<li class="chapter" data-level="2.3" data-path="unidades-de-muestreo.html"><a href="unidades-de-muestreo.html"><i class="fa fa-check"></i><b>2.3</b> Unidades de muestreo</a></li>
<li class="chapter" data-level="2.4" data-path="marcos-de-muestreo.html"><a href="marcos-de-muestreo.html"><i class="fa fa-check"></i><b>2.4</b> Marcos de muestreo</a></li>
<li class="chapter" data-level="2.5" data-path="sec-motivacion.html"><a href="sec-motivacion.html"><i class="fa fa-check"></i><b>2.5</b> Motivación</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sec-motivacion.html"><a href="sec-motivacion.html#la-importancia-de-considerar-el-diseño-muestral"><i class="fa fa-check"></i><b>2.5.1</b> La importancia de considerar el diseño muestral</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="parámetros-y-estimadores.html"><a href="parámetros-y-estimadores.html"><i class="fa fa-check"></i><b>2.6</b> Parámetros y estimadores</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="parámetros-y-estimadores.html"><a href="parámetros-y-estimadores.html#ajustes-adicionales-de-los-pesos"><i class="fa fa-check"></i><b>2.6.1</b> Ajustes adicionales de los pesos</a></li>
<li class="chapter" data-level="2.6.2" data-path="parámetros-y-estimadores.html"><a href="parámetros-y-estimadores.html#importancia-de-los-ajustes"><i class="fa fa-check"></i><b>2.6.2</b> Importancia de los ajustes</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="estimación-de-totales.html"><a href="estimación-de-totales.html"><i class="fa fa-check"></i><b>2.7</b> Estimación de totales</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="estimación-de-totales.html"><a href="estimación-de-totales.html#ejemplo-ilustrativo-1"><i class="fa fa-check"></i><b>2.7.1</b> Ejemplo ilustrativo</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="efecto-del-diseño-deff.html"><a href="efecto-del-diseño-deff.html"><i class="fa fa-check"></i><b>2.8</b> Efecto del diseño (DEFF)</a></li>
<li class="chapter" data-level="2.9" data-path="muestreo-estratificado-aleatorio-simple-con-dos-etapas.html"><a href="muestreo-estratificado-aleatorio-simple-con-dos-etapas.html"><i class="fa fa-check"></i><b>2.9</b> Muestreo estratificado aleatorio simple con dos etapas</a></li>
<li class="chapter" data-level="2.10" data-path="práctica-en-r.html"><a href="práctica-en-r.html"><i class="fa fa-check"></i><b>2.10</b> Práctica en <code>R</code></a></li>
<li class="chapter" data-level="2.11" data-path="calibrando-con-r.html"><a href="calibrando-con-r.html"><i class="fa fa-check"></i><b>2.11</b> Calibrando con <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="del-manejo-de-datos-al-análisis-de-encuestas-complejas-en-r.html"><a href="del-manejo-de-datos-al-análisis-de-encuestas-complejas-en-r.html"><i class="fa fa-check"></i><b>3</b> Del manejo de datos al análisis de encuestas complejas en R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="fundamentos-básicos-de-r-y-rstudio.html"><a href="fundamentos-básicos-de-r-y-rstudio.html"><i class="fa fa-check"></i><b>3.1</b> Fundamentos básicos de R y Rstudio</a></li>
<li class="chapter" data-level="3.2" data-path="paquetes-para-el-análisis-de-encuestas.html"><a href="paquetes-para-el-análisis-de-encuestas.html"><i class="fa fa-check"></i><b>3.2</b> Paquetes para el análisis de encuestas</a></li>
<li class="chapter" data-level="3.3" data-path="paquetes-complementarios-para-la-manipulación-y-visualización-de-datos.html"><a href="paquetes-complementarios-para-la-manipulación-y-visualización-de-datos.html"><i class="fa fa-check"></i><b>3.3</b> Paquetes complementarios para la manipulación y visualización de datos</a></li>
<li class="chapter" data-level="3.4" data-path="creación-de-proyectos-en-r.html"><a href="creación-de-proyectos-en-r.html"><i class="fa fa-check"></i><b>3.4</b> Creación de proyectos en <code>R</code></a></li>
<li class="chapter" data-level="3.5" data-path="lectura-de-bases-de-datos-y-manipulación.html"><a href="lectura-de-bases-de-datos-y-manipulación.html"><i class="fa fa-check"></i><b>3.5</b> Lectura de bases de datos y manipulación</a></li>
<li class="chapter" data-level="3.6" data-path="el-operador-pipe.html"><a href="el-operador-pipe.html"><i class="fa fa-check"></i><b>3.6</b> El operador <code>pipe</code></a></li>
<li class="chapter" data-level="3.7" data-path="transformación-y-resumen-de-datos.html"><a href="transformación-y-resumen-de-datos.html"><i class="fa fa-check"></i><b>3.7</b> Transformación y resumen de datos</a></li>
<li class="chapter" data-level="3.8" data-path="diferencias-entre-el-análisis-tradicional-y-el-análisis-de-encuestas-complejas.html"><a href="diferencias-entre-el-análisis-tradicional-y-el-análisis-de-encuestas-complejas.html"><i class="fa fa-check"></i><b>3.8</b> Diferencias entre el análisis tradicional y el análisis de encuestas complejas</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análisis-de-las-variables-continuas-en-encuestas-de-hogares.html"><a href="análisis-de-las-variables-continuas-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4</b> Análisis de las variables continuas en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lectura-de-bases-de-datos-y-definición-del-diseño-muestral.html"><a href="lectura-de-bases-de-datos-y-definición-del-diseño-muestral.html"><i class="fa fa-check"></i><b>4.1</b> Lectura de bases de datos y definición del diseño muestral</a></li>
<li class="chapter" data-level="4.2" data-path="estimación-de-totales-y-medias.html"><a href="estimación-de-totales-y-medias.html"><i class="fa fa-check"></i><b>4.2</b> Estimación de totales y medias</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estimación-de-totales-y-medias.html"><a href="estimación-de-totales-y-medias.html#estimación-puntual"><i class="fa fa-check"></i><b>4.2.1</b> Estimación puntual</a></li>
<li class="chapter" data-level="4.2.2" data-path="estimación-de-totales-y-medias.html"><a href="estimación-de-totales-y-medias.html#estimación-de-totales-1"><i class="fa fa-check"></i><b>4.2.2</b> Estimación de totales</a></li>
<li class="chapter" data-level="4.2.3" data-path="estimación-de-totales-y-medias.html"><a href="estimación-de-totales-y-medias.html#estimación-de-la-media-e-intervalo-de-confianza"><i class="fa fa-check"></i><b>4.2.3</b> Estimación de la media e intervalo de confianza</a></li>
<li class="chapter" data-level="4.2.4" data-path="estimación-de-totales-y-medias.html"><a href="estimación-de-totales-y-medias.html#estimación-de-medidas-de-localización-y-dispersión"><i class="fa fa-check"></i><b>4.2.4</b> Estimación de medidas de localización y dispersión</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="estimación-del-coeficiente-de-gini-en-encuestas-de-hogares.html"><a href="estimación-del-coeficiente-de-gini-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.3</b> Estimación del coeficiente de Gini en encuestas de hogares</a></li>
<li class="chapter" data-level="4.4" data-path="análisis-de-correlación-en-encuestas-de-hogares.html"><a href="análisis-de-correlación-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.4</b> Análisis de correlación en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="análisis-de-correlación-en-encuestas-de-hogares.html"><a href="análisis-de-correlación-en-encuestas-de-hogares.html#ajuste-al-diseño-muestral"><i class="fa fa-check"></i><b>4.4.1</b> Ajuste al diseño muestral</a></li>
<li class="chapter" data-level="4.4.2" data-path="análisis-de-correlación-en-encuestas-de-hogares.html"><a href="análisis-de-correlación-en-encuestas-de-hogares.html#expresión-formal"><i class="fa fa-check"></i><b>4.4.2</b> Expresión formal</a></li>
<li class="chapter" data-level="4.4.3" data-path="análisis-de-correlación-en-encuestas-de-hogares.html"><a href="análisis-de-correlación-en-encuestas-de-hogares.html#implementación-en-r"><i class="fa fa-check"></i><b>4.4.3</b> Implementación en R</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="pruebas-de-hipótesis.html"><a href="pruebas-de-hipótesis.html"><i class="fa fa-check"></i><b>4.5</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="pruebas-de-hipótesis.html"><a href="pruebas-de-hipótesis.html#planteamiento-general"><i class="fa fa-check"></i><b>4.5.1</b> Planteamiento general</a></li>
<li class="chapter" data-level="4.5.2" data-path="pruebas-de-hipótesis.html"><a href="pruebas-de-hipótesis.html#prueba-para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>4.5.2</b> Prueba para la diferencia de medias</a></li>
<li class="chapter" data-level="4.5.3" data-path="pruebas-de-hipótesis.html"><a href="pruebas-de-hipótesis.html#estadístico-de-prueba-e-intervalo-de-confianza"><i class="fa fa-check"></i><b>4.5.3</b> Estadístico de prueba e intervalo de confianza</a></li>
<li class="chapter" data-level="4.5.4" data-path="pruebas-de-hipótesis.html"><a href="pruebas-de-hipótesis.html#ejemplo-aplicado-en-r"><i class="fa fa-check"></i><b>4.5.4</b> Ejemplo aplicado en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="estimación-de-razones.html"><a href="estimación-de-razones.html"><i class="fa fa-check"></i><b>4.6</b> Estimación de razones</a>
<ul>
<li class="chapter" data-level="" data-path="estimación-de-razones.html"><a href="estimación-de-razones.html#implementación-computacional-en-r"><i class="fa fa-check"></i>Implementación computacional en <code>R</code></a></li>
<li class="chapter" data-level="" data-path="estimación-de-razones.html"><a href="estimación-de-razones.html#interpretación-aplicada"><i class="fa fa-check"></i>Interpretación aplicada</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="estimando-contrastes-en-encuestas-de-hogares.html"><a href="estimando-contrastes-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.7</b> Estimando contrastes en encuestas de hogares</a></li>
</ul></li>
<li class="divider"></li>
<li><a Análisis de encuestas con R </a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de encuestas con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimando-contrastes-en-encuestas-de-hogares" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Estimando contrastes en encuestas de hogares<a href="estimando-contrastes-en-encuestas-de-hogares.html#estimando-contrastes-en-encuestas-de-hogares" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En muchas ocasiones, en encuestas de hogares se requiere comparar más de dos poblaciones al mismo tiempo, por ejemplo, comparar los ingresos medios de los hogares en 3 regiones o municipalidades en la postpandemia con el fin de verificar y sectorizar aquellas municipalidades o regiones donde más impacto en el desempleo y falta de ingresos tuvo el Covid-19 en los hogares. En casos como estos la diferencia de media que estudiamos en capítulos anteriores se queda corta dado que permite solo comprar parejas de poblaciones y por ende que, hacer contraste resulta una muy buena alternativa para abordar este tipo de problemas.</p>
<p>Recurriendo en las definiciones que se han trabajado en este capítulo, un contraste es una combinación lineal de parámetros de la forma:</p>
<p><span class="math display">\[\begin{eqnarray*}
f\left(\theta _{1},\theta_{2},...,\theta_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}\theta_{j}
\end{eqnarray*}\]</span></p>
<p>Una estimación de esta función está dada por:</p>
<p><span class="math display">\[\begin{eqnarray*}
f\left(\hat{\theta}_{1},\hat{\theta}_{2},...,\hat{\theta}_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}\hat{\theta}_{j}
\end{eqnarray*}\]</span></p>
<p>cuya varianza del estimador se calcula como sigue:</p>
<p><span class="math display">\[\begin{eqnarray*}
var\left(\sum_{j=1}^{J}a_{j}\hat{\theta}_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}^{2}var\left(\hat{\theta}_{j}\right)+2\times\sum_{j=1}^{J-1}\sum_{k&gt;j}^{J}a_{j}a_{k}\,cov\left(\hat{\theta}_{j},\hat{\theta}_{k}\right)
\end{eqnarray*}\]</span></p>
<p>Los procedimientos metodológicos para implementar los contrastes en diseños de muestreo complejos están desarrolladas en la función <code>svycontrast</code>. A continuación, se muestra el uso de dicha función para el cálculo de contraste en la base de datos de ejemplo, comparando el promedio de ingresos por región.</p>
<p>Como primer ejemplo, se realizará la comparación de dos poblaciones, las regiones Norte y Sur (<span class="math inline">\(\bar{Y}_{Norte} - \bar{Y}_{Sur}\)</span>) y luego sí se compararán todas las regiones.</p>
<p>Puesto que esto es un contraste en donde hay 5 regiones y solo se construirá el contraste para la región Norte y la Sur, el contraste queda definido de la siguiente manera:</p>
<p><span class="math display">\[\begin{eqnarray*}
&amp; 1\times\hat{\bar{Y}}_{Norte}+\left(-1\right)\times\hat{\bar{Y}}_{Sur}+0\times\hat{\bar{Y}}_{Centro}+0\times\hat{\bar{Y}}_{Occidente}+0\times\hat{\bar{Y}}_{Oriente}
\end{eqnarray*}\]</span></p>
<p>que de forma matricial queda de la siguiente manera:</p>
<p><span class="math display">\[\begin{eqnarray*}
&amp; \left[1,\,-1,\,0,\,0,\,0\right]\times\left[\begin{array}{c}
\hat{\bar{Y}}_{Norte}\\
\hat{\bar{Y}}_{Sur}\\
\hat{\bar{Y}}_{Centro}\\
\hat{\bar{Y}}_{Occidente}\\
\hat{\bar{Y}}_{Oriente}
\end{array}\right]
\end{eqnarray*}\]</span></p>
<p>Como se puede observar, en este caso el vector de contraste es <span class="math inline">\(\left[1,\,-1,\,0,\,0,\,0\right]\)</span>.</p>
<p>Ahora bien, para realizar el procesos de la construcción del estimador del contraste y su varianza estimada paso a paso se inicia con calcular las medias estimadas por región con la función <code>svyby</code> como se muestra a continuación:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb101-1" tabindex="-1"></a>prom_region <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>Income,</span>
<span id="cb101-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb101-2" tabindex="-1"></a>                      <span class="at">by =</span> <span class="sc">~</span>Region,</span>
<span id="cb101-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb101-3" tabindex="-1"></a>                      <span class="at">design =</span> diseno,</span>
<span id="cb101-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb101-4" tabindex="-1"></a>                      <span class="at">FUN =</span> svymean,</span>
<span id="cb101-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb101-5" tabindex="-1"></a>                      <span class="at">na.rm=</span>T,</span>
<span id="cb101-6"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb101-6" tabindex="-1"></a>                      <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb101-7"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb101-7" tabindex="-1"></a>                      <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb101-8"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb101-8" tabindex="-1"></a>prom_region</span></code></pre></div>
<pre><code>##              Region Income   se ci_l ci_u
## Norte         Norte    552 51.5  451  653
## Sur             Sur    626 58.8  510  741
## Centro       Centro    651 57.9  537  764
## Occidente Occidente    517 43.2  432  602
## Oriente     Oriente    542 69.0  406  677</code></pre>
<p>La función <code>svyby</code> permite aplicar una función, en este caso la media (svymean) por región (by) utilizando el diseño muestral empleado (design). Las demás componentes de la función ya se han utilizado previamente. Como resultado de aplicar esta función se obtienen las medias estimadas de los ingresos por región. Se tomarán solo los ingresos medios estimados de las regiones Norte y Sur y calcularemos su diferencia:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb103-1" tabindex="-1"></a><span class="co"># Paso 1: diferencia de estimaciones (Norte - Sur)</span></span>
<span id="cb103-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb103-2" tabindex="-1"></a><span class="fl">552.4</span> <span class="sc">-</span> <span class="fl">625.8</span></span></code></pre></div>
<pre><code>## [1] -73.4</code></pre>
<p>El paso siguiente es calcular la matriz de varianzas y covarianzas y de allí extraer las varianzas y covarianzas de las regiones Norte y Sur:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb105-1" tabindex="-1"></a><span class="co"># Paso 2: Matriz de varianzas y covarianzas</span></span>
<span id="cb105-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb105-2" tabindex="-1"></a><span class="fu">vcov</span>(prom_region)</span></code></pre></div>
<pre><code>##              Norte      Sur  Centro Occidente  Oriente
## Norte     3064.715    0.000    0.00     0.000    0.000
## Sur          0.000 3894.476    0.00     0.000    0.000
## Centro       0.000    0.000 3778.42     0.000    0.000
## Occidente    0.000    0.000    0.00  2136.359    0.000
## Oriente      0.000    0.000    0.00     0.000 5135.854</code></pre>
<p>Para calcular el error estándar de la diferencia (contraste) se usará las propiedades de la varianza como es
<span class="math inline">\(se\left(\hat{\bar{y}}_{Norte}-\hat{\bar{y}}_{Sur}\right)=\sqrt{var\left(\hat{\bar{y}}_{Norte}\right)+var\left(\hat{\bar{y}}_{Sur}\right)-2\,cov\left(\hat{\bar{y}}_{Norte},\hat{\bar{y}}_{Sur}\right)}\)</span> tenemos:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb107-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">3065</span> <span class="sc">+</span> <span class="dv">3894</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 83.4</code></pre>
<p>Finalmente, la función <code>svycontrast</code> nos devuelve el contraste estimado y su error estándar. Los argumentos de esta función son los promedios de los ingresos estimados (stat) y las constantes de contraste (contrasts).</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb109-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_region,</span>
<span id="cb109-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb109-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">diff_NS =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb109-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb109-3" tabindex="-1"></a>            <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##         contrast diff_NS
## diff_NS    -73.4    78.2</code></pre>
<p>Obteniendo como resultado que los ingresos medios estimados para la región Sur es 73.4 unidades monetarias mayor que los ingresos en la región Norte con un error estándar de 83.42 unidades.</p>
<p>Ahora bien, si el objetivo es estimar los siguientes contrastes:</p>
<ul>
<li><span class="math inline">\(\bar{Y}_{Norte} - \bar{Y}_{Centro}\)</span>,</li>
<li><span class="math inline">\(\bar{Y}_{Sur}-\bar{Y}_{Centro}\)</span></li>
<li><span class="math inline">\(\bar{Y}_{Occidente}-\bar{Y}_{Oriente}\)</span></li>
</ul>
<p>Que escritas de forma matricial se tiene:</p>
<p><span class="math display">\[
\left[\begin{array}{ccccc}
1 &amp; 0 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 1 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 0 &amp; 0 &amp; 1 &amp; -1
\end{array}\right]
\]</span></p>
<p>Ahora, aplicando la función <code>svycontrast</code> en R se obtiene:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb111-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_region,</span>
<span id="cb111-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb111-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb111-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb111-3" tabindex="-1"></a>                             <span class="at">Norte_sur =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb111-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb111-4" tabindex="-1"></a>                             <span class="at">Sur_centro =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb111-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb111-5" tabindex="-1"></a>                             <span class="at">Occidente_Oriente =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span>                               <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##                   contrast   SE
## Norte_sur            -98.4 77.5
## Sur_centro           -25.0 82.5
## Occidente_Oriente    -24.7 81.4</code></pre>
<p>De lo cual se puede concluir que, las regiones con los ingresos medios de los hogares más similares son la región sur y la región centro.</p>
<p>También es posible construir contraste en variables que estén correlacionadas. Por ejemplo, Ingreso y Sexo. Como se hizo en el ejemplo anterior, se inicia con el promedio estimado por sexo.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb113-1" tabindex="-1"></a>prom_sexo <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>Income,</span>
<span id="cb113-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb113-2" tabindex="-1"></a>                   <span class="at">by =</span> <span class="sc">~</span>Sex,</span>
<span id="cb113-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb113-3" tabindex="-1"></a>                   <span class="at">design =</span> diseno,</span>
<span id="cb113-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb113-4" tabindex="-1"></a>                   <span class="at">FUN =</span> svymean,</span>
<span id="cb113-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb113-5" tabindex="-1"></a>                   <span class="at">na.rm=</span>T,</span>
<span id="cb113-6"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb113-6" tabindex="-1"></a>                   <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb113-7"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb113-7" tabindex="-1"></a>                   <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb113-8"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb113-8" tabindex="-1"></a>prom_sexo</span></code></pre></div>
<pre><code>##           Sex Income   se ci_l ci_u
## Female Female    558 24.4  510  605
## Male     Male    586 33.0  521  651</code></pre>
<p>El contraste a estimar es:</p>
<p><span class="math display">\[ \bar{Y}_{F} - \bar{Y}_{M}\]</span>
Por tanto, usando la función <code>svycontrast</code> se obtiene el contraste estimado:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb115-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_sexo,</span>
<span id="cb115-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb115-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">diff_Sexo =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb115-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb115-3" tabindex="-1"></a>            <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##           contrast diff_Sexo
## diff_Sexo    -28.3      19.8</code></pre>
<p>Obteniendo como resultado que, en promedio, los hombres obtienen 28.3 unidades monetarias más que las mujeres con una desviación de 20.76.</p>
<p>Otra posibilidad es poder obtener resultados agregados, por ejemplo:</p>
<p><span class="math inline">\(\hat{\bar{y}}_{Norte}+\hat{\bar{y}}_{Sur} +\hat{\bar{y}}_{Centro}\)</span></p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb117-1" tabindex="-1"></a>sum_region <span class="ot">&lt;-</span> <span class="fu">svyby</span>( <span class="sc">~</span> Income,  <span class="sc">~</span> Region,</span>
<span id="cb117-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb117-2" tabindex="-1"></a>                     diseno, svytotal, <span class="at">na.rm =</span> T,</span>
<span id="cb117-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb117-3" tabindex="-1"></a>                     <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb117-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb117-4" tabindex="-1"></a>                     <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb117-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb117-5" tabindex="-1"></a>sum_region</span></code></pre></div>
<pre><code>##              Region   Income      se     ci_l     ci_u
## Norte         Norte 14277323 1392251 11548561 17006085
## Sur             Sur 16068151 1773242 12592661 19543640
## Centro       Centro 16483319 2248031 12077259 20889378
## Occidente Occidente 16853540 1708656 13504635 20202444
## Oriente     Oriente 22111335 2687097 16844721 27377949</code></pre>
<p>La matriz de contraste queda como:
<span class="math display">\[
\left[\begin{array}{cccccc}
1 &amp; 1 &amp; 1 &amp; 0 &amp; 0
\end{array}\right]
\]</span>
el procedimiento en R es:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb119-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> sum_region,</span>
<span id="cb119-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb119-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb119-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb119-3" tabindex="-1"></a>                             <span class="at">Agregado_NCS =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>))) <span class="sc">%&gt;%</span>                        <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##              contrast Agregado_NCS
## Agregado_NCS 46828792      3183770</code></pre>
<p>Por otro lado, si se desean obtener los promedios por categorías. Por ejemplo:</p>
<p><span class="math display">\[
\hat{\bar{y}}_{Edad} = \frac{1}{k}\sum_{k=1}^K\hat{\bar{y}}_{k}
\]</span>
donde <span class="math inline">\(K\)</span> es el número de categorías de la variable. En R se hace de la siguiente manera:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb121-1" tabindex="-1"></a>prom_edad <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>Income,</span>
<span id="cb121-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb121-2" tabindex="-1"></a>                   <span class="at">by =</span> <span class="sc">~</span>CatAge,</span>
<span id="cb121-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb121-3" tabindex="-1"></a>                   <span class="at">design =</span>  diseno,</span>
<span id="cb121-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb121-4" tabindex="-1"></a>                   <span class="at">FUN =</span> svymean,</span>
<span id="cb121-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb121-5" tabindex="-1"></a>                   <span class="at">na.rm=</span>T,</span>
<span id="cb121-6"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb121-6" tabindex="-1"></a>                   <span class="at">covmat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb121-7"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb121-7" tabindex="-1"></a>prom_edad</span></code></pre></div>
<pre><code>##              CatAge Income   se
## 0-5             0-5    464 27.2
## 6-15           6-15    512 33.3
## 16-30         16-30    607 35.5
## 31-45         31-45    573 25.0
## 46-60         46-60    763 55.4
## Más de 60 Más de 60    467 29.2</code></pre>
<p>Cuya matriz de contraste estaría dada por:
<span class="math display">\[
\left[\begin{array}{cccccc}
\frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6}
\end{array}\right]
\]</span></p>
<p>El procedimiento en R es:</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb123-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_edad,</span>
<span id="cb123-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb123-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb123-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb123-3" tabindex="-1"></a>                             <span class="at">agregado_edad =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)))             <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##               contrast agregado_edad
## agregado_edad      564            24</code></pre>
<p>Puesto que los contrastes, como ya se mencionó, es una función lineal de parámetros, se puede también realizar contraste con parámetros tipo razón. Por ejemplo, la relación de gastos contra ingresos por sexo. A continuación, se muestran los códigos computacionales:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb125-1" tabindex="-1"></a>razon_sexo <span class="ot">&lt;-</span> <span class="fu">svyby</span>( <span class="at">formula =</span> <span class="sc">~</span>Income,</span>
<span id="cb125-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb125-2" tabindex="-1"></a>                     <span class="at">by =</span> <span class="sc">~</span>Sex,</span>
<span id="cb125-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb125-3" tabindex="-1"></a>                     <span class="at">denominator =</span> <span class="sc">~</span>Expenditure,</span>
<span id="cb125-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb125-4" tabindex="-1"></a>                     <span class="at">design =</span> diseno,</span>
<span id="cb125-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb125-5" tabindex="-1"></a>                     <span class="at">FUN =</span> svyratio,</span>
<span id="cb125-6"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb125-6" tabindex="-1"></a>                     <span class="at">na.rm=</span>T, <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb125-7"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb125-7" tabindex="-1"></a>                     <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb125-8"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb125-8" tabindex="-1"></a>razon_sexo</span></code></pre></div>
<pre><code>##           Sex Income/Expenditure se.Income/Expenditure     ci_l     ci_u
## Female Female           1.519060            0.04582607 1.429243 1.608878
## Male     Male           1.564762            0.07044239 1.426698 1.702827</code></pre>
<p>Cuya estimación de contraste sería:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb127-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> razon_sexo,</span>
<span id="cb127-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb127-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb127-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb127-3" tabindex="-1"></a>                             <span class="at">diff_sexo =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##           contrast diff_sexo
## diff_sexo  -0.0457    0.0416</code></pre>
<p>de lo que se puede concluir que la diferencia de las proporciones es 0.045 en favor de los hombres.</p>

<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div class="csl-entry">
Bache, S. M., &amp; Wickham, H. (2025). <em>magrittr: A Forward-Pipe Operator for R</em>. <a href="https://doi.org/10.32614/CRAN.package.magrittr">https://doi.org/10.32614/CRAN.package.magrittr</a>
</div>
<div class="csl-entry">
Bautista, L. (1998). Diseños de muestreo estadístico. <em>Universidad Nacional de Colombia</em>.
</div>
<div class="csl-entry">
Binder, D. A. (1983). On the variances of asymptotically normal estimators from complex surveys. <em>International Statistical Review/Revue Internationale de Statistique</em>, 279-292.
</div>
<div class="csl-entry">
Binder, D. A., &amp; Kovacevic, M. S. (1995). Estimating some measures of income inequality from survey data: an application of the estimating equations approach. <em>Survey Methodology</em>, <em>21</em>, 137-146.
</div>
<div class="csl-entry">
Bruch, C., Münnich, R., &amp; Zins, S. (2011). Variance estimation for complex surveys. <em>Deliverable D3</em>, <em>1</em>.
</div>
<div class="csl-entry">
Cochran, W. G. (1977). <em>Sampling techniques</em>. john wiley &amp; sons.
</div>
<div class="csl-entry">
Efron, B. (1979). Bootstrap methods: Another look at the jackknife. <em>The Annals of Statistics</em>, <em>7</em>(1), 1-26. <a href="https://doi.org/10.1214/aos/1176344552">https://doi.org/10.1214/aos/1176344552</a>
</div>
<div class="csl-entry">
Freedman Ellis, G., &amp; Schneider, B. (2024). <em>srvyr: ’dplyr’-Like Syntax for Summary Statistics of Survey Data</em>. <a href="https://doi.org/10.32614/CRAN.package.srvyr">https://doi.org/10.32614/CRAN.package.srvyr</a>
</div>
<div class="csl-entry">
Gambino, J. G., &amp; Nascimento Silva, P. L. do. (2009). Sampling and estimation in household surveys. En <em>Handbook of Statistics</em> (Vol. 29, pp. 407-439). Elsevier.
</div>
<div class="csl-entry">
Gutiérrez, H. A. (2016). <em>Estrategias de muestreo: diseño de encuestas y estimación de parámetros</em> (Segunda edición). Ediciones de la U.
</div>
<div class="csl-entry">
Gutiérrez, H. A. (2020a). <em>samplesize4surveys: Sample Size Calculations for Complex Surveys</em>. <a href="https://doi.org/10.32614/CRAN.package.samplesize4surveys">https://doi.org/10.32614/CRAN.package.samplesize4surveys</a>
</div>
<div class="csl-entry">
Gutiérrez, H. A. (2020b). <em>TeachingSampling: Selection of Samples and Parameter Estimation in Finite Population</em>. <a href="https://doi.org/10.32614/CRAN.package.TeachingSampling">https://doi.org/10.32614/CRAN.package.TeachingSampling</a>
</div>
<div class="csl-entry">
Gutiérrez, H. A., &amp; Babativa-Márquez, G. (2023). <em>Efectos de diseño para indicadores sociales en Am<span>é</span>rica Latina: función generalizada de varianza para estimadores directos provenientes de encuestas de hogares</em> (LC/TS.2023/95 106). Comisi<span>ó</span>n Econ<span>ó</span>mica para Am<span>é</span>rica Latina y el Caribe (CEPAL), Naciones Unidas. <a href="https://repositorio.cepal.org/server/api/core/bitstreams/feb8c8be-6434-41f2-8fd9-f12f71a0739a/content">https://repositorio.cepal.org/server/api/core/bitstreams/feb8c8be-6434-41f2-8fd9-f12f71a0739a/content</a>
</div>
<div class="csl-entry">
Hansen, M. H., Hurwitz, W. N., Madow, W. G., et al. (1953). <em>Sample survey methods and theory</em>.
</div>
<div class="csl-entry">
Hansen, M. H., &amp; Steinberg, J. (1956). Control of errors in surveys. <em>Biometrics</em>, <em>12</em>(4), 462-474.
</div>
<div class="csl-entry">
Heeringa, S. G., West, B. T., Heeringa, S. G., &amp; Berglund, P. A. (2017). <em>Applied survey data analysis</em>. chapman; hall/CRC.
</div>
<div class="csl-entry">
Jacob, G., Pessoa, D., &amp; Damico, A. (2024). <em>Poverty and Inequality with Complex Survey Data</em>. <a href="https://www.convey-r.org/">https://www.convey-r.org/</a>
</div>
<div class="csl-entry">
Kalton, G., &amp; Flores-Cervantes, I. (2003). Weighting methods. <em>Journal of official statistics</em>, <em>19</em>(2), 81.
</div>
<div class="csl-entry">
Kish, L. (1965). <em>Survey sampling.</em>
</div>
<div class="csl-entry">
Korn, E. L., &amp; Graubard, B. I. (1995). Analysis of large health surveys: accounting for the sampling design. <em>Journal of the Royal Statistical Society: Series A (Statistics in Society)</em>, <em>158</em>(2), 263-295.
</div>
<div class="csl-entry">
Kovacevic, M. S., &amp; Binder, D. A. (1997). Variance estimation for measures of income inequality and polarization-the estimating equations approach. <em>Journal of Official Statistics</em>, <em>13</em>(1), 41.
</div>
<div class="csl-entry">
Kovar, J., Rao, J., &amp; Wu, C. (1988). Bootstrap and other methods to measure errors in survey estimates. <em>Canadian Journal of Statistics</em>, <em>16</em>(S1), 25-45.
</div>
<div class="csl-entry">
Langel, M., &amp; Tillé, Y. (2013). Variance estimation of the Gini index: revisiting a result several times published. <em>Journal of the Royal Statistical Society Series A: Statistics in Society</em>, <em>176</em>(2), 521-540.
</div>
<div class="csl-entry">
Loomis, D., Richardson, D. B., &amp; Elliott, L. (2005). Poisson regression analysis of ungrouped data. <em>Occupational and environmental medicine</em>, <em>62</em>(5), 325-329.
</div>
<div class="csl-entry">
Lumley, T. (2010). <em>Complex Surveys: A Guide to Analysis Using R: A Guide to Analysis Using R</em>. John Wiley; Sons.
</div>
<div class="csl-entry">
Lumley, T. (2024). <em>survey: analysis of complex survey samples</em>.
</div>
<div class="csl-entry">
Naciones Unidas. (2009). <em>Diseño de Muestras para Encuestas de Hogares: Directrices Prácticas.</em> Naciones Unidas. <a href="https://unstats.un.org/unsd/publication/seriesf/seriesf_98s.pdf">https://unstats.un.org/unsd/publication/seriesf/seriesf_98s.pdf</a>
</div>
<div class="csl-entry">
Osier, G. (2009). Variance estimation for complex indicators of poverty and inequality using linearization techniques. <em>Survey research methods</em>, <em>3</em>, 167-195.
</div>
<div class="csl-entry">
Park, I., Winglee, M., Clark, J., Rust, K., Sedlak, A., &amp; Morganstein, D. (2003). Design Effects and Survey Planning. <em>Proceedings of the Section on Survey Research Methods</em>, 3179-3186. <a href="https://www.asasrms.org/Proceedings/y2003/Files/JSM2003-000156.pdf">https://www.asasrms.org/Proceedings/y2003/Files/JSM2003-000156.pdf</a>
</div>
<div class="csl-entry">
Rao, J. N. K., Wu, C. F. J., &amp; Yue, K. (1992). Some recent work on resampling methods for complex surveys. <em>Survey Methodology</em>, <em>18</em>, 209-217.
</div>
<div class="csl-entry">
Santana Sepúlveda, S., &amp; Mateos Farfán, E. (2014). <em>El arte de programar en R: un lenguaje para la estadística</em>. México: Instituto Mexicano de Tecnología del Agua. UNESCO. Comité Nacional Mexicano del Programa Hidrológico Internacional.
</div>
<div class="csl-entry">
Särndal, C.-E., &amp; Lundström, S. (2005). <em>Estimation in surveys with nonresponse</em>. John Wiley &amp; Sons.
</div>
<div class="csl-entry">
Särndal, C.-E., Swensson, B., &amp; Wretman, J. (2003). <em>Model assisted survey sampling</em>. Springer Science &amp; Business Media.
</div>
<div class="csl-entry">
Tellez Piñerez, C. F., &amp; Lemus Polanía, D. F. (2015). <em>Estadística Descriptiva y Probabilidad con aplicaciones en R</em>. Fundación Universitaria Los Libertadore.
</div>
<div class="csl-entry">
Tillé, Y., &amp; Matei, A. (2025). <em>sampling: Survey Sampling</em>. <a href="https://doi.org/10.32614/CRAN.package.sampling">https://doi.org/10.32614/CRAN.package.sampling</a>
</div>
<div class="csl-entry">
Valliant, R. (2024). <em>svydiags: Regression Model Diagnostics for Survey Data</em>. <a href="https://doi.org/10.32614/CRAN.package.svydiags">https://doi.org/10.32614/CRAN.package.svydiags</a>
</div>
<div class="csl-entry">
Valliant, R., &amp; Zipf, G. (2025). <em>PracTools: Designing and Weighting Survey Samples</em>. <a href="https://doi.org/10.32614/CRAN.package.PracTools">https://doi.org/10.32614/CRAN.package.PracTools</a>
</div>
<div class="csl-entry">
Wickham, H. (2019). <em>Advanced R</em> (2.ª ed.). Chapman; Hall/CRC. <a href="https://adv-r.hadley.nz/">https://adv-r.hadley.nz/</a>
</div>
<div class="csl-entry">
Wickham, H., &amp; Grolemund, G. (2017). <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data</em>. O’Reilly Media. <a href="https://r4ds.hadley.nz/">https://r4ds.hadley.nz/</a>
</div>
<div class="csl-entry">
Wickham, H., Miller, E., &amp; Smith, D. (2025). <em>haven: Import and Export ’SPSS’, ’Stata’ and ’SAS’ Files</em>. <a href="https://doi.org/10.32614/CRAN.package.haven">https://doi.org/10.32614/CRAN.package.haven</a>
</div>
<div class="csl-entry">
Wickham, H., Navarro, D., &amp; Pedersen, T. L. (2023). <em>ggplot2: Elegant Graphics for Data Analysis</em> (3.ª ed.). Springer. <a href="https://doi.org/10.1007/978-3-319-24277-4">https://doi.org/10.1007/978-3-319-24277-4</a>
</div>
<div class="csl-entry">
Wolter, K. M., &amp; Wolter, K. M. (2007). <em>Introduction to variance estimation</em> (Vol. 53). Springer.
</div>
</div>
</div>
<!-- </div> -->









            </section>

          </div>
        </div>
      </div>
<a href="estimación-de-razones.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/psirusteam/2021ASDA/04-Continuas.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["Análisis de encuestas con R.pdf", "Análisis de encuestas con R.epub", "Análisis de encuestas con R.mobi"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  },
  "tconfig": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
